import './csv.test';
import './isNumber.test';
import './renderTemplate.test';
import './hashData.test';
import './casing.test';
import './data.test';
import './token.test';
import './password.test';
import './csrf.test';
