version: '3.7'

services:
  postgres:
    image: postgres:12
    volumes:
      - pgbackups:/var/pgbackups
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  resizer:
    build: ./resizer
    command: server
    volumes:
      - resizer-staging:/run/resizer

  app:
    build: ./
    volumes:
      - resizer-staging:/run/resizer
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    environment:
      - APP_DB_HOST=postgres
      - PYTHONUNBUFFERED=1

volumes:
  pgbackups:
  resizer-staging:
